POST http://localhost:8000/api/transactions/
Content-Type: application/json

{
    "text": "salaire Juin",
    "amount": -2000.00
}

###
GET http://localhost:8000/api/transactions/

###
DELETE http://localhost:8000/api/transactions/41755b9e-bbb6-4e59-a97c-f3bce5f82a07/


